server:
  port: 8080
#picture src Virtual address mapping
web:
  upload-path: F:\pic\
spring:
  datasource:
    username: root
    password: mysql199858
    url: jdbc:mysql://localhost:3306/bookcity?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
      static-path-pattern: /**
  resources:
      static-locations: classpath:/,classpath:/Mapper/,classpath:/static/,file:${web.upload-path},classpath:/templates/

mybatis:
  mapper-locations: classpath:Mapper/*.xml
  type-aliases-package: com.itzidan.domain

#showSql
logging:
  level:
    com:
      example:
        mapper : debug

mail:
     qqaccount: 857504753@qq.com
     password: pkxecllqdtpwbdfa
#picture src Virtual address mapping


